"""Engine enums generated from the vendored OpenAPI spec. DO NOT EDIT.

Generated by scripts/pin_engine.py from engine API version 0.7.0.
A contract test asserts these match ``schema/openapi3.json``.
"""

from __future__ import annotations

from enum import StrEnum

__all__ = [
    "BondPriceType",
    "BootstrapTrait",
    "BusinessDayConvention",
    "CPIInterpolationType",
    "Calendar",
    "CallabilityType",
    "CapFloorType",
    "CdsEngineType",
    "CdsHelperModel",
    "CdsIsdaAccrualBias",
    "CdsIsdaForwardsInCouponPeriod",
    "CdsIsdaNumericalFix",
    "CdsQuoteType",
    "CmsPricerType",
    "CmsYieldCurveModel",
    "Compounding",
    "DateGenerationRule",
    "DayCounter",
    "EquityBarrierMonitoring",
    "EquityBarrierType",
    "EquityModelType",
    "EquityOptionType",
    "EquitySettlementType",
    "ExerciseType",
    "FRAType",
    "Frequency",
    "InflationCurveKind",
    "InflationCurveMeasure",
    "Interpolator",
    "IrModelType",
    "ModelParamMode",
    "ProtectionSide",
    "RateAveragingType",
    "SettlementMethod",
    "SettlementType",
    "SurfaceInterpolator2D",
    "SwapType",
    "SwaptionStrikeKind",
    "SwaptionVolKind",
    "TimeUnit",
    "VolSurfaceShape",
    "VolatilityType",
    "YoYInflationCapFloorEngineType",
]


class DayCounter(StrEnum):
    """Engine enum ``DayCounter`` (15 values)."""

    Actual360 = "Actual360"
    Actual365Fixed = "Actual365Fixed"
    Actual365NoLeap = "Actual365NoLeap"
    ActualActual = "ActualActual"
    ActualActualISMA = "ActualActualISMA"
    ActualActualBond = "ActualActualBond"
    ActualActualISDA = "ActualActualISDA"
    ActualActualHistorical = "ActualActualHistorical"
    ActualActual365 = "ActualActual365"
    ActualActualAFB = "ActualActualAFB"
    ActualActualEuro = "ActualActualEuro"
    Business252 = "Business252"
    One = "One"
    Simple = "Simple"
    Thirty360 = "Thirty360"


class Interpolator(StrEnum):
    """Engine enum ``Interpolator`` (5 values)."""

    BackwardFlat = "BackwardFlat"
    ForwardFlat = "ForwardFlat"
    Linear = "Linear"
    LogCubic = "LogCubic"
    LogLinear = "LogLinear"


class SurfaceInterpolator2D(StrEnum):
    """Engine enum ``SurfaceInterpolator2D`` (2 values)."""

    Bilinear = "Bilinear"
    Bicubic = "Bicubic"


class BootstrapTrait(StrEnum):
    """Engine enum ``BootstrapTrait`` (6 values)."""

    Discount = "Discount"
    FwdRate = "FwdRate"
    InterpolatedDiscount = "InterpolatedDiscount"
    InterpolatedFwd = "InterpolatedFwd"
    InterpolatedZero = "InterpolatedZero"
    ZeroRate = "ZeroRate"


class TimeUnit(StrEnum):
    """Engine enum ``TimeUnit`` (9 values)."""

    Days = "Days"
    Hours = "Hours"
    Microseconds = "Microseconds"
    Milliseconds = "Milliseconds"
    Minutes = "Minutes"
    Months = "Months"
    Seconds = "Seconds"
    Weeks = "Weeks"
    Years = "Years"


class Calendar(StrEnum):
    """Engine enum ``Calendar`` (43 values)."""

    Argentina = "Argentina"
    Australia = "Australia"
    BespokeCalendar = "BespokeCalendar"
    Brazil = "Brazil"
    Canada = "Canada"
    China = "China"
    CzechRepublic = "CzechRepublic"
    Denmark = "Denmark"
    Finland = "Finland"
    Germany = "Germany"
    HongKong = "HongKong"
    Hungary = "Hungary"
    Iceland = "Iceland"
    India = "India"
    Indonesia = "Indonesia"
    Israel = "Israel"
    Italy = "Italy"
    Japan = "Japan"
    Mexico = "Mexico"
    NewZealand = "NewZealand"
    Norway = "Norway"
    NullCalendar = "NullCalendar"
    Poland = "Poland"
    Romania = "Romania"
    Russia = "Russia"
    SaudiArabia = "SaudiArabia"
    Singapore = "Singapore"
    Slovakia = "Slovakia"
    SouthAfrica = "SouthAfrica"
    SouthKorea = "SouthKorea"
    Sweden = "Sweden"
    Switzerland = "Switzerland"
    TARGET = "TARGET"
    Taiwan = "Taiwan"
    Turkey = "Turkey"
    Ukraine = "Ukraine"
    UnitedKingdom = "UnitedKingdom"
    UnitedStates = "UnitedStates"
    UnitedStatesGovernmentBond = "UnitedStatesGovernmentBond"
    UnitedStatesNERC = "UnitedStatesNERC"
    UnitedStatesNYSE = "UnitedStatesNYSE"
    UnitedStatesSettlement = "UnitedStatesSettlement"
    WeekendsOnly = "WeekendsOnly"


class BusinessDayConvention(StrEnum):
    """Engine enum ``BusinessDayConvention`` (7 values)."""

    Following = "Following"
    HalfMonthModifiedFollowing = "HalfMonthModifiedFollowing"
    ModifiedFollowing = "ModifiedFollowing"
    ModifiedPreceding = "ModifiedPreceding"
    Nearest = "Nearest"
    Preceding = "Preceding"
    Unadjusted = "Unadjusted"


class Frequency(StrEnum):
    """Engine enum ``Frequency`` (13 values)."""

    Annual = "Annual"
    Bimonthly = "Bimonthly"
    Biweekly = "Biweekly"
    Daily = "Daily"
    EveryFourthMonth = "EveryFourthMonth"
    EveryFourthWeek = "EveryFourthWeek"
    Monthly = "Monthly"
    NoFrequency = "NoFrequency"
    Once = "Once"
    OtherFrequency = "OtherFrequency"
    Quarterly = "Quarterly"
    Semiannual = "Semiannual"
    Weekly = "Weekly"


class DateGenerationRule(StrEnum):
    """Engine enum ``DateGenerationRule`` (8 values)."""

    Backward = "Backward"
    CDS = "CDS"
    Forward = "Forward"
    OldCDS = "OldCDS"
    ThirdWednesday = "ThirdWednesday"
    Twentieth = "Twentieth"
    TwentiethIMM = "TwentiethIMM"
    Zero = "Zero"


class CdsEngineType(StrEnum):
    """Engine enum ``CdsEngineType`` (2 values)."""

    MidPoint = "MidPoint"
    ISDA = "ISDA"


class CdsHelperModel(StrEnum):
    """Engine enum ``CdsHelperModel`` (2 values)."""

    MidPoint = "MidPoint"
    ISDA = "ISDA"


class CdsQuoteType(StrEnum):
    """Engine enum ``CdsQuoteType`` (2 values)."""

    ParSpread = "ParSpread"
    Upfront = "Upfront"


class CdsIsdaNumericalFix(StrEnum):
    """Engine enum ``CdsIsdaNumericalFix`` (2 values)."""

    None_ = "None"
    Taylor = "Taylor"


class CdsIsdaAccrualBias(StrEnum):
    """Engine enum ``CdsIsdaAccrualBias`` (2 values)."""

    HalfDayBias = "HalfDayBias"
    NoBias = "NoBias"


class CdsIsdaForwardsInCouponPeriod(StrEnum):
    """Engine enum ``CdsIsdaForwardsInCouponPeriod`` (2 values)."""

    Flat = "Flat"
    Piecewise = "Piecewise"


class Compounding(StrEnum):
    """Engine enum ``Compounding`` (4 values)."""

    Compounded = "Compounded"
    Continuous = "Continuous"
    Simple = "Simple"
    SimpleThenCompounded = "SimpleThenCompounded"


class RateAveragingType(StrEnum):
    """Engine enum ``RateAveragingType`` (2 values)."""

    Compound = "Compound"
    Simple = "Simple"


class SwapType(StrEnum):
    """Engine enum ``SwapType`` (2 values)."""

    Payer = "Payer"
    Receiver = "Receiver"


class FRAType(StrEnum):
    """Engine enum ``FRAType`` (2 values)."""

    Long = "Long"
    Short = "Short"


class CapFloorType(StrEnum):
    """Engine enum ``CapFloorType`` (3 values)."""

    Cap = "Cap"
    Floor = "Floor"
    Collar = "Collar"


class CallabilityType(StrEnum):
    """Engine enum ``CallabilityType`` (2 values)."""

    Call = "Call"
    Put = "Put"


class ExerciseType(StrEnum):
    """Engine enum ``ExerciseType`` (3 values)."""

    European = "European"
    Bermudan = "Bermudan"
    American = "American"


class SettlementType(StrEnum):
    """Engine enum ``SettlementType`` (2 values)."""

    Physical = "Physical"
    Cash = "Cash"


class SettlementMethod(StrEnum):
    """Engine enum ``SettlementMethod`` (4 values)."""

    PhysicalOTC = "PhysicalOTC"
    PhysicalCleared = "PhysicalCleared"
    CollateralizedCashPrice = "CollateralizedCashPrice"
    ParYieldCurve = "ParYieldCurve"


class ProtectionSide(StrEnum):
    """Engine enum ``ProtectionSide`` (2 values)."""

    Buyer = "Buyer"
    Seller = "Seller"


class VolatilityType(StrEnum):
    """Engine enum ``VolatilityType`` (3 values)."""

    Normal = "Normal"
    Lognormal = "Lognormal"
    ShiftedLognormal = "ShiftedLognormal"


class VolSurfaceShape(StrEnum):
    """Engine enum ``VolSurfaceShape`` (6 values)."""

    Constant = "Constant"
    AtmMatrix2D = "AtmMatrix2D"
    SmileCube3D = "SmileCube3D"
    SurfaceFromPrices = "SurfaceFromPrices"
    SabrParams = "SabrParams"
    SabrCalibrate = "SabrCalibrate"


class YoYInflationCapFloorEngineType(StrEnum):
    """Engine enum ``YoYInflationCapFloorEngineType`` (3 values)."""

    Black = "Black"
    UnitDisplacedBlack = "UnitDisplacedBlack"
    Bachelier = "Bachelier"


class SwaptionVolKind(StrEnum):
    """Engine enum ``SwaptionVolKind`` (5 values)."""

    Constant = "Constant"
    AtmMatrix2D = "AtmMatrix2D"
    SmileCube3D = "SmileCube3D"
    SabrParams = "SabrParams"
    SabrCalibrate = "SabrCalibrate"


class SwaptionStrikeKind(StrEnum):
    """Engine enum ``SwaptionStrikeKind`` (2 values)."""

    Absolute = "Absolute"
    SpreadFromATM = "SpreadFromATM"


class InflationCurveKind(StrEnum):
    """Engine enum ``InflationCurveKind`` (2 values)."""

    ZeroInflation = "ZeroInflation"
    YoYInflation = "YoYInflation"


class InflationCurveMeasure(StrEnum):
    """Engine enum ``InflationCurveMeasure`` (2 values)."""

    ZeroRate = "ZeroRate"
    YoYRate = "YoYRate"


class CPIInterpolationType(StrEnum):
    """Engine enum ``CPIInterpolationType`` (3 values)."""

    AsIndex = "AsIndex"
    Flat = "Flat"
    Linear = "Linear"


class BondPriceType(StrEnum):
    """Engine enum ``BondPriceType`` (2 values)."""

    Clean = "Clean"
    Dirty = "Dirty"


class IrModelType(StrEnum):
    """Engine enum ``IrModelType`` (4 values)."""

    Black = "Black"
    ShiftedBlack = "ShiftedBlack"
    Bachelier = "Bachelier"
    HullWhiteLattice = "HullWhiteLattice"


class ModelParamMode(StrEnum):
    """Engine enum ``ModelParamMode`` (2 values)."""

    Explicit = "Explicit"
    Calibrate = "Calibrate"


class CmsPricerType(StrEnum):
    """Engine enum ``CmsPricerType`` (3 values)."""

    LinearTsr = "LinearTsr"
    HaganAnalytic = "HaganAnalytic"
    HaganNumeric = "HaganNumeric"


class CmsYieldCurveModel(StrEnum):
    """Engine enum ``CmsYieldCurveModel`` (4 values)."""

    Standard = "Standard"
    ExactYield = "ExactYield"
    ParallelShifts = "ParallelShifts"
    NonParallelShifts = "NonParallelShifts"


class EquityModelType(StrEnum):
    """Engine enum ``EquityModelType`` (2 values)."""

    BlackScholesAnalytic = "BlackScholesAnalytic"
    BinomialCRR = "BinomialCRR"


class EquityOptionType(StrEnum):
    """Engine enum ``EquityOptionType`` (2 values)."""

    Call = "Call"
    Put = "Put"


class EquitySettlementType(StrEnum):
    """Engine enum ``EquitySettlementType`` (2 values)."""

    Physical = "Physical"
    Cash = "Cash"


class EquityBarrierType(StrEnum):
    """Engine enum ``EquityBarrierType`` (4 values)."""

    DownIn = "DownIn"
    UpIn = "UpIn"
    DownOut = "DownOut"
    UpOut = "UpOut"


class EquityBarrierMonitoring(StrEnum):
    """Engine enum ``EquityBarrierMonitoring`` (2 values)."""

    Continuous = "Continuous"
    Discrete = "Discrete"
