"""The methodology pages: how the engine computes what it returns, cited to its
own documentation and source at the pinned tag; plus ``connector-analytics``,
what THIS server computes on top (bumps, DV01 differences, reprice diffs),
cited to this repository's source at a commit.

The pages under ``docs/methodology/`` are GENERATED by ``scripts/pin_engine.py``
/ ``scripts/methodology_gen.py`` (rules in ``scripts/methodology_rules.py``);
nothing here is hand-written. This module only loads them and maps response
metrics to the topic to consult.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from quantra_mcp.errors import LocalValidationError

METHODOLOGY_DIR = Path(__file__).resolve().parent / "docs" / "methodology"
URI_PREFIX = "quantra://methodology"


@lru_cache(maxsize=1)
def load_index() -> dict[str, Any]:
    data: dict[str, Any] = json.loads((METHODOLOGY_DIR / "INDEX.json").read_text())
    return data


def slugs() -> list[str]:
    return [t["slug"] for t in load_index()["topics"]]


def repos() -> dict[str, str]:
    """The two repositories every citation links into (engine, connector)."""
    out: dict[str, str] = dict(load_index()["repos"])
    return out


def topics() -> list[dict[str, Any]]:
    """One row per topic: slug, title, summary, uri, source (engine | connector),
    citation count."""
    return [
        {
            "slug": t["slug"],
            "title": t["title"],
            "summary": t["summary"],
            "uri": f"{URI_PREFIX}/{t['slug']}",
            "source": t.get("source", "engine"),
            "citations": len(t["citations"]),
        }
        for t in load_index()["topics"]
    ]


def _find(slug: str) -> dict[str, Any]:
    key = slug.strip().lower().replace("_", "-").replace(" ", "-")
    for t in load_index()["topics"]:
        if t["slug"] == key:
            return dict(t)
    raise LocalValidationError(
        f"unknown methodology topic {slug!r}; topics: {slugs()}",
        [{"path": "/topic", "message": f"one of {slugs()}"}],
    )


def get_topic(slug: str) -> dict[str, Any]:
    """The page: metadata, the markdown, every citation and the documented gaps."""
    t = _find(slug)
    index = load_index()
    source = t.get("source", "engine")
    return {
        "topic": t["slug"],
        "title": t["title"],
        "summary": t["summary"],
        "uri": f"{URI_PREFIX}/{t['slug']}",
        "source": source,
        "engine_tag": index["engine_tag"],
        "engine_sha": index["engine_sha"],
        "connector_sha": index["connector_sha"],
        "repository": index["repos"][source],
        "markdown": (METHODOLOGY_DIR / t["file"]).read_text(),
        "citations": [c["ref"] for c in t["citations"]],
        "links": [c["url"] for c in t["citations"]],
        "not_documented": t["gaps"],
    }


def topic_for_metric(field: str) -> str | None:
    """Which topic explains a response field (``npv`` -> ``npv``, ``dv01`` ->
    ``greeks-bump-and-reprice``, ...); None when the field is not mapped."""
    mapping: dict[str, str] = load_index()["metric_topics"]
    return mapping.get(field)
