"""Pin the vendored engine contract to a git tag of the engine repository.

Copies, from an engine checkout at the given tag (read with ``git show``,
never touching the working tree of that repository):

* ``jsonserver/openapi/openapi3.json``  -> ``src/quantra_mcp/schema/openapi3.json``
* ``docs/http-api.md``                  -> ``src/quantra_mcp/docs/http-api.md``
* ``docs/versioning.md``                -> ``src/quantra_mcp/docs/versioning.md``

and writes ``src/quantra_mcp/schema/PIN`` (``<tag> <commit sha>``) plus
``src/quantra_mcp/schema/enums_generated.py`` (one ``StrEnum`` per engine enum,
so tool arguments are typed with the engine's own values).

Usage::

    uv run python scripts/pin_engine.py --engine-repo /path/to/quantraserver --tag v0.7.0
"""

from __future__ import annotations

import argparse
import json
import keyword
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "quantra_mcp"
SCHEMA_DIR = PKG / "schema"
DOCS_DIR = PKG / "docs"

FILES = {
    "jsonserver/openapi/openapi3.json": SCHEMA_DIR / "openapi3.json",
    "docs/http-api.md": DOCS_DIR / "http-api.md",
    "docs/versioning.md": DOCS_DIR / "versioning.md",
}

ENUM_PREFIX = "quantra_enums_"


def git_show(repo: Path, tag: str, path: str) -> bytes:
    return subprocess.run(
        ["git", "-C", str(repo), "show", f"{tag}:{path}"],
        check=True,
        capture_output=True,
    ).stdout


def git_sha(repo: Path, tag: str) -> str:
    out = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", f"{tag}^{{commit}}"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return out.strip()


def render_enums(spec: dict[str, object]) -> str:
    components = spec["components"]
    assert isinstance(components, dict)
    schemas = components["schemas"]
    assert isinstance(schemas, dict)
    info = spec["info"]
    assert isinstance(info, dict)
    lines = [
        '"""Engine enums generated from the vendored OpenAPI spec. DO NOT EDIT.',
        "",
        f"Generated by scripts/pin_engine.py from engine API version {info['version']}.",
        "A contract test asserts these match ``schema/openapi3.json``.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import StrEnum",
        "",
        "__all__ = [",
    ]
    names: list[str] = []
    for name in schemas:
        if name.startswith(ENUM_PREFIX):
            names.append(name.removeprefix(ENUM_PREFIX))
    lines.extend(f'    "{n}",' for n in names)
    lines.append("]")
    for n in names:
        schema = schemas[ENUM_PREFIX + n]
        assert isinstance(schema, dict)
        values = schema["enum"]
        assert isinstance(values, list)
        lines.append("")
        lines.append("")
        lines.append(f"class {n}(StrEnum):")
        lines.append(f'    """Engine enum ``{n}`` ({len(values)} values)."""')
        lines.append("")
        for v in values:
            assert isinstance(v, str)
            member = v + "_" if keyword.iskeyword(v) else v
            lines.append(f'    {member} = "{v}"')
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--engine-repo", required=True, type=Path)
    parser.add_argument("--tag", required=True)
    args = parser.parse_args(argv)
    repo: Path = args.engine_repo
    tag: str = args.tag

    sha = git_sha(repo, tag)
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    for src, dest in FILES.items():
        data = git_show(repo, tag, src)
        dest.write_bytes(data)
        print(f"{src} -> {dest.relative_to(ROOT)} ({len(data)} bytes)", file=sys.stderr)

    spec = json.loads((SCHEMA_DIR / "openapi3.json").read_text())
    (SCHEMA_DIR / "enums_generated.py").write_text(render_enums(spec))
    (SCHEMA_DIR / "PIN").write_text(f"{tag} {sha}\n")
    print(f"PIN = {tag} {sha} (API {spec['info']['version']})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
